// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2ma0KaWqvOdjq8FU9qanbXeNi2ocilwo',
    appId: '1:798822824658:android:318b718ab0ca2bcd18cb0b',
    messagingSenderId: '798822824658',
    projectId: 'evfinder-4ff3d',
    storageBucket: 'evfinder-4ff3d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDaCiRO2Pgdl68GXJ5vyDy14efHKIrQKEA',
    appId: '1:798822824658:ios:2357ca886ca8a62d18cb0b',
    messagingSenderId: '798822824658',
    projectId: 'evfinder-4ff3d',
    storageBucket: 'evfinder-4ff3d.firebasestorage.app',
    androidClientId: '798822824658-eukc0nt9scg7jd75u0ofhfq0afqo79qf.apps.googleusercontent.com',
    iosClientId: '798822824658-ldgr9ng7ic73lsf182tdvos79vvhhqsi.apps.googleusercontent.com',
    iosBundleId: 'com.example.evfinderFront',
  );
}
